# Generated by Django 4.1.7 on 2023-03-25 16:31

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EssayQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_english",
                    ckeditor.fields.RichTextField(verbose_name="question english"),
                ),
                (
                    "question_arabic",
                    ckeditor.fields.RichTextField(verbose_name="question arabic"),
                ),
                (
                    "right_answer_english",
                    ckeditor.fields.RichTextField(verbose_name="right answer english"),
                ),
                (
                    "right_answer_arabic",
                    ckeditor.fields.RichTextField(verbose_name="right answer arabic"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.teacher",
                        verbose_name="teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "essay question",
                "verbose_name_plural": "essay questions",
            },
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name_english",
                    models.CharField(max_length=511, verbose_name="name english"),
                ),
                (
                    "name_arabic",
                    models.CharField(max_length=511, verbose_name="name arabic"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="created at"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="updated at"),
                ),
                ("price", models.IntegerField(verbose_name="price")),
                ("is_demo", models.BooleanField(default=False, verbose_name="is demo")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="is active"),
                ),
                (
                    "essay_questions",
                    models.ManyToManyField(
                        to="exams.essayquestion", verbose_name="essay questions"
                    ),
                ),
            ],
            options={
                "verbose_name": "exam",
                "verbose_name_plural": "exams",
            },
        ),
        migrations.CreateModel(
            name="TrueFalseQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_english",
                    ckeditor.fields.RichTextField(verbose_name="question english"),
                ),
                (
                    "question_arabic",
                    ckeditor.fields.RichTextField(verbose_name="question arabic"),
                ),
                (
                    "right_answer",
                    models.CharField(
                        choices=[("T", "True"), ("F", "False")],
                        max_length=1,
                        verbose_name="right answer",
                    ),
                ),
                (
                    "cause_english",
                    ckeditor.fields.RichTextField(verbose_name="cause english"),
                ),
                (
                    "cause_arabic",
                    ckeditor.fields.RichTextField(verbose_name="cause arabic"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.teacher",
                        verbose_name="teacher",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MultipleChoiceQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "question_english",
                    ckeditor.fields.RichTextField(verbose_name="question english"),
                ),
                (
                    "question_arabic",
                    ckeditor.fields.RichTextField(verbose_name="question arabic"),
                ),
                (
                    "cause_english",
                    ckeditor.fields.RichTextField(verbose_name="cause english"),
                ),
                (
                    "cause_arabic",
                    ckeditor.fields.RichTextField(verbose_name="cause arabic"),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="main.teacher",
                        verbose_name="teacher",
                    ),
                ),
            ],
            options={
                "verbose_name": "MCQ",
                "verbose_name_plural": "MCQs",
            },
        ),
        migrations.CreateModel(
            name="ExamsGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_english",
                    models.CharField(max_length=511, verbose_name="name english"),
                ),
                (
                    "name_arabic",
                    models.CharField(max_length=511, verbose_name="name arabic"),
                ),
                ("price", models.IntegerField(verbose_name="price")),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="is active"),
                ),
                (
                    "exams",
                    models.ManyToManyField(to="exams.exam", verbose_name="exams"),
                ),
                (
                    "students",
                    models.ManyToManyField(
                        to="main.normaluser", verbose_name="students"
                    ),
                ),
            ],
            options={
                "verbose_name": "exams group",
                "verbose_name_plural": "exams groups",
            },
        ),
        migrations.AddField(
            model_name="exam",
            name="mcq_questions",
            field=models.ManyToManyField(
                to="exams.multiplechoicequestion", verbose_name="MCQ questions"
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="students",
            field=models.ManyToManyField(to="main.normaluser", verbose_name="students"),
        ),
        migrations.AddField(
            model_name="exam",
            name="teacher",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="main.teacher",
                verbose_name="teacher",
            ),
        ),
        migrations.AddField(
            model_name="exam",
            name="true_false_questions",
            field=models.ManyToManyField(
                to="exams.truefalsequestion", verbose_name="true-false questions"
            ),
        ),
        migrations.CreateModel(
            name="EssayQuestoionKeyword",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_english",
                    models.CharField(max_length=255, verbose_name="content english"),
                ),
                (
                    "content_arabic",
                    models.CharField(max_length=255, verbose_name="content arabic"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.essayquestion",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "essay question keyword",
                "verbose_name_plural": "essay question keywords",
            },
        ),
        migrations.CreateModel(
            name="ChoiceAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content_english",
                    models.CharField(max_length=255, verbose_name="content english"),
                ),
                (
                    "content_arabic",
                    models.CharField(max_length=255, verbose_name="content arabic"),
                ),
                (
                    "is_right",
                    models.BooleanField(default=False, verbose_name="is it right"),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="exams.multiplechoicequestion",
                        verbose_name="question",
                    ),
                ),
            ],
            options={
                "verbose_name": "choice",
                "verbose_name_plural": "choices",
            },
        ),
    ]
