# Generated by Django 4.1.7 on 2023-03-28 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_alter_exam_description_arabic_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='examsgroup',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='price'),
        ),
    ]
