# Generated by Django 4.1.7 on 2023-03-30 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_price_alter_examsgroup_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_finish',
            field=models.BooleanField(default=False, verbose_name='is finish'),
        ),
    ]
