# Generated by Django 4.1.7 on 2023-04-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0009_essayquestion_is_finish_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="EssayQuestoionKeyword",
            new_name="EssayQuestionKeyword",
        ),
    ]
