# Generated by Django 4.1.7 on 2023-04-12 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0012_takingexamsession'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='takingexamsession',
            options={'verbose_name': 'taking exam session', 'verbose_name_plural': 'taking exam sessions'},
        ),
        migrations.AddField(
            model_name='takingexamsession',
            name='duration',
            field=models.DurationField(default=None, verbose_name='duration'),
            preserve_default=False,
        ),
    ]
