# Generated by Django 4.1.7 on 2023-03-26 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="normaluser",
            name="personal_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="personal image"
            ),
        ),
    ]
