# Generated by Django 4.1.7 on 2023-03-27 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_normaluser_personal_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='birthdate',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='nationality',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='phone_number',
        ),
    ]
